program Compiler;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  JsonFlow4D.Arrays in '..\Source\JSON\Composition\JsonFlow4D.Arrays.pas',
  JsonFlow4D.Composer.Enhanced in '..\Source\JSON\Composition\JsonFlow4D.Composer.Enhanced.pas',
  JsonFlow4D.Composer in '..\Source\JSON\Composition\JsonFlow4D.Composer.pas',
  JsonFlow4D.Composer.Pool in '..\Source\JSON\Composition\JsonFlow4D.Composer.Pool.pas',
  JsonFlow4D.Objects in '..\Source\JSON\Composition\JsonFlow4D.Objects.pas',
  JsonFlow4D.Pair in '..\Source\JSON\Composition\JsonFlow4D.Pair.pas',
  JsonFlow4D.Converters in '..\Source\JSON\Core\JsonFlow4D.Converters.pas',
  JsonFlow4D.Interfaces in '..\Source\JSON\Core\JsonFlow4D.Interfaces.pas',
  JsonFlow4D.Utils in '..\Source\JSON\Core\JsonFlow4D.Utils.pas',
  JsonFlow4D.Value in '..\Source\JSON\Core\JsonFlow4D.Value.pas',
  JsonFlow4D.Converter.Dataset in '..\Source\JSON\IO\JsonFlow4D.Converter.Dataset.pas',
  JsonFlow4D.Converter.XML in '..\Source\JSON\IO\JsonFlow4D.Converter.XML.pas',
  JsonFlow4D.Navigator in '..\Source\JSON\IO\JsonFlow4D.Navigator.pas',
  JsonFlow4D.Reader in '..\Source\JSON\IO\JsonFlow4D.Reader.pas',
  JsonFlow4D.Serializer.Attributes in '..\Source\JSON\IO\JsonFlow4D.Serializer.Attributes.pas',
  JsonFlow4D.Serializer.CircularRef in '..\Source\JSON\IO\JsonFlow4D.Serializer.CircularRef.pas',
  JsonFlow4D.Serializer in '..\Source\JSON\IO\JsonFlow4D.Serializer.pas',
  JsonFlow4D.Serializer.Pool in '..\Source\JSON\IO\JsonFlow4D.Serializer.Pool.pas',
  JsonFlow4D.Writer in '..\Source\JSON\IO\JsonFlow4D.Writer.pas',
  JsonFlow4D.MiddlewareDatatime in '..\Source\JSON\Middleware\JsonFlow4D.MiddlewareDatatime.pas',
  JsonFlow4D in '..\Source\JsonFlow4D.pas',
  JsonFlow4D.SchemaComposer in '..\Source\Schema\Composition\JsonFlow4D.SchemaComposer.pas',
  JsonFlow4D.SchemaNavigator in '..\Source\Schema\Composition\JsonFlow4D.SchemaNavigator.pas',
  JsonFlow4D.AsyncValidator in '..\Source\Schema\Core\JsonFlow4D.AsyncValidator.pas',
  JsonFlow4D.ErrorListPool in '..\Source\Schema\Core\JsonFlow4D.ErrorListPool.pas',
  JsonFlow4D.Metrics in '..\Source\Schema\Core\JsonFlow4D.Metrics.pas',
  JsonFlow4D.PersistentCache in '..\Source\Schema\Core\JsonFlow4D.PersistentCache.pas',
  JsonFlow4D.Reports in '..\Source\Schema\Core\JsonFlow4D.Reports.pas',
  JsonFlow4D.Schema in '..\Source\Schema\Core\JsonFlow4D.Schema.pas',
  JsonFlow4D.ValidationEngine in '..\Source\Schema\Core\JsonFlow4D.ValidationEngine.pas',
  JsonFlow4D.ValidationRules in '..\Source\Schema\Core\JsonFlow4D.ValidationRules.pas',
  JsonFlow4D.SchemaReader in '..\Source\Schema\IO\JsonFlow4D.SchemaReader.pas',
  JsonFlow4D.SchemaRefIndy in '..\Source\Schema\IO\JsonFlow4D.SchemaRefIndy.pas',
  JsonFlow4D.SchemaRefSynapse in '..\Source\Schema\IO\JsonFlow4D.SchemaRefSynapse.pas',
  JsonFlow4D.FormatValidators.Brazil in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.Brazil.pas',
  JsonFlow4D.FormatValidators.BrazilianLicensePlate in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.BrazilianLicensePlate.pas',
  JsonFlow4D.FormatValidators.BrazilianPhone in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.BrazilianPhone.pas',
  JsonFlow4D.FormatValidators.CEP in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.CEP.pas',
  JsonFlow4D.FormatValidators.CNPJ in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.CNPJ.pas',
  JsonFlow4D.FormatValidators.CPF in '..\Source\Schema\Validators\Format\Brazil\JsonFlow4D.FormatValidators.CPF.pas',
  JsonFlow4D.FormatValidators.Base in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Base.pas',
  JsonFlow4D.FormatValidators.Date in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Date.pas',
  JsonFlow4D.FormatValidators.DateTime in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.DateTime.pas',
  JsonFlow4D.FormatValidators.Email in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Email.pas',
  JsonFlow4D.FormatValidators.Ipv4 in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Ipv4.pas',
  JsonFlow4D.FormatValidators.Ipv6 in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Ipv6.pas',
  JsonFlow4D.FormatValidators.Time in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Time.pas',
  JsonFlow4D.FormatValidators.Uri in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Uri.pas',
  JsonFlow4D.FormatValidators.Uuid in '..\Source\Schema\Validators\Format\JsonFlow4D.FormatValidators.Uuid.pas',
  JsonFlow4D.FormatRegistry in '..\Source\Schema\Validators\JsonFlow4D.FormatRegistry.pas',
  JsonFlow4D.FormatValidators in '..\Source\Schema\Validators\JsonFlow4D.FormatValidators.pas',
  JsonFlow4D.SchemaValidator in '..\Source\Schema\Validators\JsonFlow4D.SchemaValidator.pas',
  JsonFlow4D.ValidationRules.AdditionalProperties in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.AdditionalProperties.pas',
  JsonFlow4D.ValidationRules.AllOf in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.AllOf.pas',
  JsonFlow4D.ValidationRules.AnyOf in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.AnyOf.pas',
  JsonFlow4D.ValidationRules.Base in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Base.pas',
  JsonFlow4D.ValidationRules.Conditional in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Conditional.pas',
  JsonFlow4D.ValidationRules.Consts in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Consts.pas',
  JsonFlow4D.ValidationRules.Contains in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Contains.pas',
  JsonFlow4D.ValidationRules.Enum in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Enum.pas',
  JsonFlow4D.ValidationRules.ExclusiveMaximum in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.ExclusiveMaximum.pas',
  JsonFlow4D.ValidationRules.ExclusiveMinimum in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.ExclusiveMinimum.pas',
  JsonFlow4D.ValidationRules.Format in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Format.pas',
  JsonFlow4D.ValidationRules.Items in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Items.pas',
  JsonFlow4D.ValidationRules.Maximum in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Maximum.pas',
  JsonFlow4D.ValidationRules.MaxItems in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MaxItems.pas',
  JsonFlow4D.ValidationRules.MaxLength in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MaxLength.pas',
  JsonFlow4D.ValidationRules.MaxProperties in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MaxProperties.pas',
  JsonFlow4D.ValidationRules.Minimum in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Minimum.pas',
  JsonFlow4D.ValidationRules.MinItems in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MinItems.pas',
  JsonFlow4D.ValidationRules.MinLength in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MinLength.pas',
  JsonFlow4D.ValidationRules.MinProperties in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MinProperties.pas',
  JsonFlow4D.ValidationRules.MultipleOf in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.MultipleOf.pas',
  JsonFlow4D.ValidationRules.NotRule in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.NotRule.pas',
  JsonFlow4D.ValidationRules.OneOf in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.OneOf.pas',
  JsonFlow4D.ValidationRules.Pattern in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Pattern.pas',
  JsonFlow4D.ValidationRules.PatternProperties in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.PatternProperties.pas',
  JsonFlow4D.ValidationRules.Properties in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Properties.pas',
  JsonFlow4D.ValidationRules.PropertyNames in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.PropertyNames.pas',
  JsonFlow4D.ValidationRules.Required in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Required.pas',
  JsonFlow4D.ValidationRules.Types in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.Types.pas',
  JsonFlow4D.ValidationRules.UniqueItems in '..\Source\Schema\Validators\JsonFlow4D.ValidationRules.UniqueItems.pas';

begin
  try
    { TODO -oUser -cConsole Main : Insert code here }
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
